MyFAANStore/Controllers/ProductHistoryController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using ClosedXML.Excel;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MyFAANStore.Models;
using Store.Core;
using Store.Core.Exceptions;
using Store.Logic.Interfaces;

namespace MyFAANStore.Controllers
{
    public class ProductHistoryController : Controller
    {
        IProductHistoryLogic ProductHistoryLogic;
        IDepartmentLogic DepartmentLogic;
        IProductLogic ProductLogic;
        IProductAnalysisLogic ProductAnalysisLogic;
        ProductAnalysis InventoryAnalysis;
        public ProductHistoryController(IProductHistoryLogic ProductHistoryLogic, IDepartmentLogic departmentLogic, IProductLogic productLogic, IProductAnalysisLogic productAnalysisLogic)
        {
            this.ProductHistoryLogic = ProductHistoryLogic;
            this.ProductLogic = productLogic;
            this.DepartmentLogic = departmentLogic;
            this.ProductAnalysisLogic = productAnalysisLogic;
            InventoryAnalysis = this.ProductAnalysisLogic.GetToday();
        }
        // GET: ProductHistory
        public ActionResult Index()
        {
            return View();
        }


        // GET: ProductHistory
        public ActionResult Suply()
        {
            ProductHistoryModel model = new ProductHistoryModel { };
            model.Departments = this.DepartmentLogic.GetAllViews();
            model.Products = this.ProductLogic.GetAllViews()?.OrderBy(x => x.Text);
            return View(model);
        }
        [HttpPost]
        public ActionResult Suply(ProductHistoryModel model)
        {
            try
            {
                //TODO: Add insert logic here
                if (ModelState.IsValid)
                {
                    var theProduct = this.ProductLogic.GetByID(model.ProductID.Value);

                    var productHistory = new ProductHistory
                    {
                        TheProduct = theProduct,
                        TheDepartment = model.Department,
                        Quantity = model.Quantity.Value,
                        QuantityAfter = theProduct.Quantity + model.Quantity.Value,
                        QuantityBefore = theProduct.Quantity,
                        Date = DateTime.Now,
                        RequestType = Store.Core.Enums.RequestType.Receive,
                        VoucherNo = theProduct.Code,
                        NameOfRepresentative = model.NameOfRepresentative,
                        PhoneOfRepresentative = model.PhoneOfRepresentative,
                        UnitPrice =  theProduct.UnitPrice ,

                    };
                    productHistory.ValuePrice = productHistory.UnitPrice * productHistory.Quantity;
                    theProduct.Quantity = theProduct.Quantity + model.Quantity.Value;
                    this.InventoryAnalysis.TotalReceived+=model.Quantity.Value;
                    this.ProductAnalysisLogic.Update(this.InventoryAnalysis);
                    this.ProductHistoryLogic.Save(productHistory);
                    this.ProductLogic.Update(theProduct);
                    this.ProductLogic.SaveChanges();


                    ViewBag.Success = $"{theProduct.Name} Successfully Received";
                    ModelState.Clear();
                    return View("Verify", new ProductVerifyModel { IsSupply = true });

                }

               
            }


            catch (Exception ex)
            {
                ViewBag.Error = "System Error Occured. Please try again shortly";
            }
           
            return View(model);
        }

        // GET: ProductHistory
        public ActionResult Verify( bool IsSupply)
        {
            ProductVerifyModel model = new ProductVerifyModel {  IsSupply = IsSupply };
            return View(model);
        }
        [HttpPost]
        public ActionResult Verify(ProductVerifyModel model)
        {
            try
            {

                //TODO: Add insert logic here
                if (ModelState.IsValid)
                {
                    var theProduct = this.ProductLogic.GetByCode(model.ProductCode);

                    if (theProduct == null) throw new FailureException("Invalid Code. No product exists with this Code. Please check the list of available products and try again");


                    ProductHistoryModel history = new ProductHistoryModel { ProductCode = model.ProductCode, ProductName = theProduct.Name, QuantityRemaining = theProduct.Quantity, ProductID = theProduct.ID };

                    if (!model.IsSupply)
                        return View("MakeRequest", history);
                    else
                        return View("Suply", history);

                }
            }
            catch (FailureException ex)
            {
                ViewBag.Error = ex.Message;
            }

            catch (Exception ex)
            {
                ViewBag.Error = "System Error Occured. Please try again shortly";

            }
            return View();
        }
        public ActionResult MakeRequest()
        {
            ProductHistoryModel model = new ProductHistoryModel { };
            model.Departments = this.DepartmentLogic.GetAllViews();
            model.Products = this.ProductLogic.GetAllViews()?.OrderBy(x => x.Text);
            return View(model);
        }
        // GET: ProductHistory
        [HttpPost]
        public ActionResult MakeRequest(ProductHistoryModel model)
        {
            try
            {
                // TODO: Add insert logic here
                if (ModelState.IsValid)
                {
                    var theProduct = this.ProductLogic.GetByID(model.ProductID.Value);


                    if (model.Quantity > theProduct.Quantity) throw new FailureException("The quantity requested is more than what is available");
                    var productHistory = new ProductHistory
                    {
                        TheProduct = theProduct,
                        TheDepartment = model.Department,
                        Quantity = model.Quantity.Value,
                        QuantityAfter = theProduct.Quantity - model.Quantity.Value,
                        QuantityBefore = theProduct.Quantity,
                        Date = DateTime.Now,
                        RequestType = Store.Core.Enums.RequestType.Issue,
                        VoucherNo = theProduct.Code,
                        NameOfRepresentative = model.NameOfRepresentative,
                        PhoneOfRepresentative = model.PhoneOfRepresentative,
                        UnitPrice=theProduct.UnitPrice
                    };
                    productHistory.ValuePrice = productHistory.UnitPrice * productHistory.Quantity;
                    theProduct.Quantity = theProduct.Quantity - model.Quantity.Value;
                    this.InventoryAnalysis.TotalIssued += model.Quantity.Value;
                    this.ProductAnalysisLogic.Update(this.InventoryAnalysis);
                    this.ProductHistoryLogic.Save(productHistory);
                    this.ProductLogic.Update(theProduct);
                    this.ProductLogic.SaveChanges();


                    ViewBag.Success = $"{theProduct.Name} Successfully Issued";
                    ModelState.Clear();
                    return View("Verify", new ProductVerifyModel { IsSupply = false });

                }


            }

            catch (FailureException ex)
            {
                ViewBag.Error = ex.Message;
            }

            catch (Exception ex)
            {
                ViewBag.Error = "System Error Occured. Please try again shortly";
            }

          
            return View(model);
        }
        // GET: ProductHistory/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ProductHistory/Create
        public ActionResult Create()
        {
            return View();
        }


        public ActionResult ViewProductHistorys(ProductHistoryViewModel model)
        {
            try
            {
                var productHistory = ProductHistoryLogic.GetAll();

                productHistory = productHistory.OrderByDescending(x => x.Date).ToList();
                var theModel = new ProductHistoryViewModel { TheProductHistories = productHistory };

                return View(theModel);
            }
            catch (Exception ex)
            {
                ViewBag.Error = "System Error Occured. Please try again shortly";
                return View();
            }
        }
        // GET: ProductHistory/Edit/5
        public ActionResult Edit(int id)
        {
            var productHistory = ProductHistoryLogic.GetByID(id);
            if (productHistory == null)
            {
                TempData["Error"] = "Invalid ID";
                return RedirectToAction("ViewProductHistorys");
            }
            ProductHistoryDetailsViewModel model = new ProductHistoryDetailsViewModel
            {
                ProductCode = productHistory.TheProduct?.Code,
                ProductName = productHistory.TheProduct?.Name,
                Date = productHistory.Date,
                Department = productHistory.TheDepartment,
                NameOfRepresentative = productHistory.NameOfRepresentative,
                PhoneOfRepresentative = productHistory.NameOfRepresentative,
                Quantity = productHistory.Quantity,
                QuantityAfter = productHistory.QuantityAfter,
                QuantityBefore = productHistory.QuantityBefore,
                RequestType = productHistory.RequestType,
                UnitPrice = productHistory.UnitPrice,
                ValuePrice = productHistory.ValuePrice
            };



            return PartialView("Details", model);
        }
        // GET: ProductHistory/Edit/5
        public ActionResult EditEntry(int id)

MyFAANStore/Views/ProductHistory/EditEntry.cshtml
@model MyFAANStore.Models.ProductHistoryModel

<div id="page_top" class="section-body">
    <div class="container-fluid">
        <div class="page-header">
            <div class="left">
                <h1 class="page-title" style="color:#21ba45 !important">Edit Entry</h1>
            </div>
            <div class="right">
                <div class="notification d-flex">
                    <button type="button" class="btn btn-facebook"><i class="fa fa-info-circle mr-2"></i>Need Help</button>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="section-body">
    <div class="container-fluid">
        <div class="row clearfix">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Supply</h3>
                    </div>
                    <div class="card-body">

                        @if (@ViewBag.Success != null)
                        {
                            <div class="alert alert-success alert-dismissible">
                                <button data-dismiss="alert" class="close"></button>
                                <p>@ViewBag.Success</p>
                            </div>

                        }
                        @if (@ViewBag.Error != null)
                        {
                            <div class="alert alert-error">
                                <button data-dismiss="alert" class="close"></button>
                                <p>@ViewBag.Error</p>
                            </div>

                        }

                        @using (Html.BeginForm("EditEntry", "ProductHistory", FormMethod.Post, new { role = "form" }))
                        {
                            @Html.HiddenFor(model => model.ProductID)
                            @Html.HiddenFor(model => model.ID)

                            @*<div class="form-group">
                <label class="form-label">Product:</label>
                @Html.DropDownListFor(model => model.ProductID, Model.Products, "--Select--", new { @class = "form-control custom-select", placeholder = "Name Of Representative" })
                @Html.ValidationMessageFor(model => model.ProductID, "", new { @class = "text-danger", @style = "color:#d14" })
            </div>*@

                            <div class="form-group">
                                <label class="form-label">Product Name</label>
                                @Html.EditorFor(model => model.ProductName, new { htmlAttributes = new { @class = "form-control", placeholder = "Product Name", @readonly = "readonly" } })
                                @Html.ValidationMessageFor(model => model.ProductName, "", new { @class = "text-danger", @style = "color:#d14" })
                            </div>
                            <div class="form-group">
                                <label class="form-label">Product Code</label>
                                @Html.EditorFor(model => model.ProductCode, new { htmlAttributes = new { @class = "form-control", placeholder = "Product Name", @readonly = "readonly" } })
                                @Html.ValidationMessageFor(model => model.ProductCode, "", new { @class = "text-danger", @style = "color:#d14" })
                            </div>
                            <div class="form-group">
                                <label class="form-label">Quantity In Store</label>
                                @Html.EditorFor(model => model.QuantityRemaining, new { htmlAttributes = new { @class = "form-control", placeholder = "Quantity In Store", @readonly = "readonly" } })
                                @Html.ValidationMessageFor(model => model.QuantityRemaining, "", new { @class = "text-danger", @style = "color:#d14" })
                            </div>

                            <div class="form-group">
                                @Html.EditorFor(model => model.Department, new { htmlAttributes = new { @class = "form-control", placeholder = "Department / Company" } })
                                @Html.ValidationMessageFor(model => model.Department, "", new { @class = "text-danger", @style = "color:#d14" })
                            </div>

                            <div class="form-group">
                                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control", placeholder = "Quantity Supplied" } })
                                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger", @style = "color:#d14" })

                            </div>

                            @*<div class="form-group">
                @Html.EditorFor(model => model.UnitPrice, new { htmlAttributes = new { @class = "form-control", placeholder = "Unit Price of Item" } })
                @Html.ValidationMessageFor(model => model.UnitPrice, "", new { @class = "text-danger", @style = "color:#d14" })
            </div>*@

                            <div class="form-group">
                                @* <label class="form-label">Supplier Rep. Name:</label>*@

                                @Html.EditorFor(model => model.NameOfRepresentative, new { htmlAttributes = new { @class = "form-control", placeholder = "Name Of Representative" } })
                                @Html.ValidationMessageFor(model => model.NameOfRepresentative, "", new { @class = "text-danger", @style = "color:#d14" })
                            </div>
                            <div class="form-group">
                                @* <label class="form-label">Supplier Rep. Phone:</label>*@
                                @Html.EditorFor(model => model.PhoneOfRepresentative, new { htmlAttributes = new { @class = "form-control", placeholder = "Phone Of Representative" } })
                                @Html.ValidationMessageFor(model => model.PhoneOfRepresentative, "", new { @class = "text-danger", @style = "color:#d14" })
                            </div>

                            <br>
                            <button type="submit" class="btn btn-primary pull-right">Update</button>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

MyFAANStore/Views/ProductHistory/Export.cshtml
@model MyFAANStore.Models.ProductHistoryExportModel
@using Store.Core.Enums

<div class="modal-header">
    <h5 class="modal-title" id="exampleModalLiveLabel">Search</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">×</span>
    </button>
</div>
<div class="modal-body">
    <div class="card">

        <div class="card-body">

            @if (@ViewBag.Success != null)
            {
                <div class="alert alert-success alert-dismissible">
                    <button data-dismiss="alert" class="close"></button>
                    <p>@ViewBag.Success</p>
                </div>

            }
            @if (@ViewBag.Error != null)
            {
                <div class="alert alert-success alert-dismissible">
                    <button data-dismiss="alert" class="close"></button>
                    <p>@ViewBag.Error</p>
                </div>

            }

                @using (Html.BeginForm("Export", "ProductHistory", FormMethod.Post, new {  role = "form" }))
                {
                    <div class="form-group">
                        <div class="input-daterange input-group" data-provide="datepicker">
                            @Html.EditorFor(model => model.FromDate, new { htmlAttributes = new { @class = "input-sm form-control", placeholder = "From" } })
                            <span class="input-group-addon range-to col-md-1">to</span>
                            @Html.EditorFor(model => model.ToDate, new { htmlAttributes = new { @class = "input-sm form-control", placeholder = "To" } })

                            @*<input type="text" class="input-sm form-control" name="end">*@
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label class="form-label">@Html.DisplayNameFor(model => model.ProductCode)</label>
                            </div>
                        </div>
                        <div class="col-md-pull-6">
                            <div class="form-group">
                                @Html.EditorFor(model => model.ProductCode, new { htmlAttributes = new { @class = "form-control", placeholder = "Product Code" } })
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label class="form-label">@Html.DisplayNameFor(model => model.RequestType)</label>
                            </div>
                        </div>
                        <div class="col-md-pull-6">
                            <div class="form-group">
                                @*<select asp-for="RequestType" asp-items="Html.GetEnumSelectList<RequestType>()">
                                        <option selected="selected" value="">Please select</option>
                                    </select>*@
                                @Html.DropDownListFor(model => model.RequestType, Html.GetEnumSelectList<RequestType>(), "--Select--", new { @class = "form-control custom-select" })
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <label class="form-label">In Department</label>
                            </div>
                        </div>
                        <div class="col-md-pull-6">
                            <div class="form-group">
                                @*<select asp-for="RequestType" asp-items="Html.GetEnumSelectList<RequestType>()">
                                        <option selected="selected" value="">Please select</option>
                                    </select>*@
                                @Html.DropDownListFor(model => model.DepartmentID, Model.Departments, "--Select--", new { @class = "form-control custom-select" })
                            </div>
                        </div>
                    </div>

                    <br>
                    <button type="submit" class="btn btn-primary pull-right" >Export</button>
                }
        </div>
    </div>
</div>
@*<div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
    </div>*@

MyFAANStore/Views/ProductHistory/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
</body>
</html>

MyFAANStore/Views/ProductHistory/Index2.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index2</title>
</head>
<body>
</body>
</html>

MyFAANStore/Views/ProductHistory/MakeRequest.cshtml
@model MyFAANStore.Models.ProductHistoryModel

<div id="page_top" class="section-body">
    <div class="container-fluid">
        <div class="page-header">
            <div class="left">
                <h1 class="page-title">Issue Product</h1>
            </div>
            <div class="right">
                <div class="notification d-flex">
                    <button type="button" class="btn btn-facebook"><i class="fa fa-info-circle mr-2"></i>Need Help</button>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="section-body">
    <div class="container-fluid">
        <div class="row clearfix">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Issue</h3>
                    </div>
                    <div class="card-body">

                        @if (@ViewBag.Success != null)
                        {
                            <div class="alert alert-success alert-dismissible">
                                <button data-dismiss="alert" class="close"></button>
                                <p>@ViewBag.Success</p>
                            </div>

                        }
                        @if (@ViewBag.Error != null)
                        {
                            <div class="alert alert-error">
                                <button data-dismiss="alert" class="close"></button>
                                <p>@ViewBag.Error</p>
                            </div>

                        }


                        @using (Html.BeginForm("MakeRequest", "ProductHistory", FormMethod.Post, new { role = "form" }))
                        {
                            @Html.HiddenFor(model => model.ProductID)
                            @*<div class="form-group">
                                    <label class="form-label">Product:</label>
                                    @Html.DropDownListFor(model => model.ProductID, Model.Products, "--Select--", new { @class = "form-control custom-select", placeholder = "Name Of Representative" })
                                    @Html.ValidationMessageFor(model => model.ProductID, "", new { @class = "text-danger", @style = "color:#d14" })
                                </div>*@

                            <div class="form-group">
                                <label class="form-label">Product Name</label>
                                @Html.EditorFor(model => model.ProductName, new { htmlAttributes = new { @class = "form-control", placeholder = "Product Name", @readonly = "readonly" } })
                                @Html.ValidationMessageFor(model => model.ProductName, "", new { @class = "text-danger", @style = "color:#d14" })
                            </div>
                            <div class="form-group">
                                <label class="form-label">Product Code</label>
                                @Html.EditorFor(model => model.ProductCode, new { htmlAttributes = new { @class = "form-control", placeholder = "Product Name", @readonly = "readonly" } })
                                @Html.ValidationMessageFor(model => model.ProductCode, "", new { @class = "text-danger", @style = "color:#d14" })
                            </div>
                            <div class="form-group">
                                <label class="form-label">Quantity In Store</label>
                                @Html.EditorFor(model => model.QuantityRemaining, new { htmlAttributes = new { @class = "form-control", placeholder = "Quantity In Store", @readonly = "readonly" } })
                                @Html.ValidationMessageFor(model => model.QuantityRemaining, "", new { @class = "text-danger", @style = "color:#d14" })
                            </div>

                            <div class="form-group">
                                @Html.EditorFor(model => model.Department, new { htmlAttributes = new { @class = "form-control", placeholder = "Department / Company" } })
                                @Html.ValidationMessageFor(model => model.Department, "", new { @class = "text-danger", @style = "color:#d14" })
                            </div>

                            <div class="form-group">
                                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control", placeholder = "Quantity Requested" } })
                                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger", @style = "color:#d14" })

                            </div>



                            <div class="form-group">
                                @* <label class="form-label">Supplier Rep. Name:</label>*@

                                @Html.EditorFor(model => model.NameOfRepresentative, new { htmlAttributes = new { @class = "form-control", placeholder = "Name Of Representative" } })
                                @Html.ValidationMessageFor(model => model.NameOfRepresentative, "", new { @class = "text-danger", @style = "color:#d14" })
                            </div>
                            <div class="form-group">
                                @* <label class="form-label">Supplier Rep. Phone:</label>*@
                                @Html.EditorFor(model => model.PhoneOfRepresentative, new { htmlAttributes = new { @class = "form-control", placeholder = "Phone Of Representative" } })
                                @Html.ValidationMessageFor(model => model.PhoneOfRepresentative, "", new { @class = "text-danger", @style = "color:#d14" })
                            </div>

                            <br>
                            <button type="submit" class="btn btn-primary pull-right">Issue</button>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

MyFAANStore/Views/ProductHistory/Verify.cshtml
@model MyFAANStore.Models.ProductVerifyModel

<div id="page_top" class="section-body">
    <div class="container-fluid">
        <div class="page-header">
            <div class="left">
                <h1 class="page-title" style="color:#21ba45 !important">Search Product</h1>
            </div>
            <div class="right">
                <div class="notification d-flex">
                    <button type="button" class="btn btn-facebook"><i class="fa fa-info-circle mr-2"></i>Need Help</button>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="section-body">
    <div class="container-fluid">
        <div class="row clearfix">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Product</h3>
                    </div>
                    <div class="card-body">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        @using (Html.BeginForm("Verify", "ProductHistory", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                        {

                            @if (@ViewBag.Success != null)
                            {
                                <div class="alert alert-success alert-dismissible">
                                    <button data-dismiss="alert" class="close"></button>
                                    <p>@ViewBag.Success</p>
                                </div>

                            }
                            @if (@ViewBag.Error != null)
                            {
                                <div class="alert alert-error">
                                    <button data-dismiss="alert" class="close"></button>
                                    <p>@ViewBag.Error</p>
                                </div>

                            }
                            @Html.AntiForgeryToken()
                            @Html.HiddenFor(model => model.IsSupply)
                            @Html.HiddenFor(model => model.IsInitialRequest)
                            <div class="input-group">

                                @Html.EditorFor(model => model.ProductCode, new { htmlAttributes = new { @class = "form-control", placeholder = "Search for.." } })
                                <span class="input-group-append"><button class="btn btn-primary" type="submit">Go!</button></span>
                                @Html.ValidationMessageFor(model => model.ProductCode, "", new { @class = "text-danger", @style = "color:#d14" })

                            </div>

                        }
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>